### ISSUE TITLE
README-zh-CN.md

### ISSUE THREAD

**Issue by wadekun** [dexteryy/spellbook-of-modern-webdev#85]
e... maybe need a README-zh-CN.md for developer that english is poor , just like me...🙂

**Comment by dexteryy** [comment]
This document consists of two kinds of content elements: the plain-text category name and the link. 

The category names are basically some proper nouns, technical terms or buzzwords which are also used in non-English-speaking regions (like China). The links all point to English-language articles or web pages which are almost impossible to be translated by this project. And It doesn't make much sense to only translate titles of these links. 

So I don't think an README-zh-CN.md would be meaningful.

How to keep all translations in sync is also a problem. https://github.com/dexteryy/spellbook-of-modern-webdev/issues/7

**Comment by iwinux** [comment]
For such simple translation, I think Google Translate would be more than sufficient....
