### ISSUE TITLE
Is protractor a alternative solution for e2e web testing?

### ISSUE THREAD

**Issue by CNaiko** [dexteryy/spellbook-of-modern-webdev#87]
In my aspect of opinion, angular team protractor is a easy-to-use e2e testing tool. Have you been consider add this into spellbook?

I admire your work. You save my tons of hours.

**Comment by dexteryy** [comment]
@CNaiko  Thanks for reminding. I have added it to 'Tooling > Testing > Web Testing > Functional Testing > Headless Browser Automation'
